# ArgoCD Application for E-commerce Microservices
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-microservices
  namespace: argocd
  labels:
    app.kubernetes.io/name: ecommerce-microservices
    app.kubernetes.io/part-of: ecommerce
spec:
  project: default
  
  # Source repository configuration
  source:
    repoURL: https://github.com/Tulasi2710/AKS-Infrastructure-Project.git
    targetRevision: HEAD
    path: k8s
    
  # Destination cluster and namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce
    
  # Sync policy configuration
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
        
  # Health check configuration
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
    
---
# ArgoCD Application for Database Components
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-database
  namespace: argocd
  labels:
    app.kubernetes.io/name: ecommerce-database
    app.kubernetes.io/part-of: ecommerce
spec:
  project: default
  
  source:
    repoURL: https://github.com/Tulasi2710/AKS-Infrastructure-Project.git
    targetRevision: HEAD
    path: k8s/database
    
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce-database
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
        
---
# ArgoCD Application for Monitoring Stack
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-monitoring
  namespace: argocd
  labels:
    app.kubernetes.io/name: ecommerce-monitoring
    app.kubernetes.io/part-of: monitoring
spec:
  project: default
  
  source:
    repoURL: https://github.com/Tulasi2710/AKS-Infrastructure-Project.git
    targetRevision: HEAD
    path: k8s/monitoring
    
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m